services:
  client:
    container_name: client
    build: ./client
    restart: on-failure
    ports:
      - "3000:3000"
    command: serve -s build
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,state.change.logger=ERROR,kafka.network.RequestChannel$=ERROR,kafka.request.logger=ERROR,kafka.coordinator.group.GroupMetadataManager=ERROR,kafka.log.LogCleaner=ERROR,state.change.logger=ERROR,kafka.authorizer.logger=ERROR"
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=256MB
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    restart: on-failure
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
      - KAFKA_URI=kafka:9092
      - JWT_SECRET_KEY=OIDU#H-298ghd-7G@#DF^))GV31286f)D^#FV^2f06f6b-!%R@R^@!1263
    depends_on:
      - kafka
      - zookeeper
    command: flask run --host 0.0.0.0 --port 5000

  websocket-server:
    build: ./ws
    container_name: websocket-server
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      - MONGODB_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - KAFKA_URI=kafka:9092
      - JWT_SECRET_KEY=OIDU#H-298ghd-7G@#DF^))GV31286f)D^#FV^2f06f6b-!%R@R^@!1263
    depends_on:
      - mongodb
      - kafka
      - zookeeper
    command: python main.py

  invite-service:
    build: ./invites
    restart: on-failure
    ports:
      - "9100:9100"
    environment:
      - JWT_SECRET_KEY=OIDU#H-298ghd-7G@#DF^))GV31286f)D^#FV^2f06f6b-!%R@R^@!1263
    command: python main.py

  email-sender:
    build: ./email-sender-service
    restart: on-failure
    ports:
      - '5100:5100'
    environment:
      - KAFKA_URI=kafka:9092
      - LOGO_PATH=https://codevoke.ru/static/logo512.png
    depends_on:
      - server
    command: python main.py

  image-service:
    build: ./image-service
    restart: on-failure
    ports:
      - '5200:5200'
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - server
    volumes:
    - ./image-service/images:/image-service/images
    command: flask run --host 0.0.0.0 --port 5200

volumes:
  pgdata: {}
  mongodb_data: {}
