export {default as RegisterPage} from './RegisterPage';
export {default as LoginPage} from './LoginPage';
export {default as ProfilePage} from './ProfilePage';
export {default as CreateGamePage} from './CreateGamePage';
export {default as OpenGamesPage} from './OpenGamesPage';
export {default as PrivateGamesPage} from './PrivateGamesPage';
export {default as GameFiltersPage} from './GameFiltersPage'
export {default as GamePage} from './GamePage'
export {default as ConnectingPage} from './ConnectingToGamePage'
export {default as DefaultPage} from './DefaultPage'
export {default as SettingsPage} from './SettingsPage'
export {default as ConfirmEmailPage} from './ConfirmEmailPage'
export {default as FriendsPage} from './FriendsPage'
export {default as SearchFriendPage} from './SearchFriendPage'